### ISSUE TITLE
HELP: Cannot start perseus 'Cannot read property 'prototype' of undefined'

### ISSUE THREAD

**Issue by weiwei5444** [Khan/perseus#80]
I can't start perseus. When I ran the command 'make server PORT=9000', it was stopped by an Error. Here is the detailed error information:

`Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/root/perseus/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/perseus/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:541:32)
make: *** [server-offline] Error 1
`
How can I fix it?

**Comment by kevinbarabash** [comment]
What version of npm are using?

**Comment by weiwei5444** [comment]
@kevinbarabash , Thank you for answering, here are the versions of npm & node:
npm -v
1.3.10

nodejs -v
v0.10.25

node -v
v7.0.0-pre

**Comment by kevinbarabash** [comment]
It's possible that this is causing the issue (from a travis-ci build): `graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`

Maybe try an earlier version of node.

**Comment by kevinptt0323** [comment]
Try `npm install webpack-dev-server@1.8.0 --save-dev`.

This command will upgrade `webpack-dev-server` in `package.json`.

The error occurs because the older version of `webpack-dev-server` uses older version of `socket.io` (0.9.17), which is not working under node 7.x.

**Comment by kevinbarabash** [comment]
@kevinptt0323 thanks for figuring that out.  This is probably something we'll want to fix.
